// Generated by CoffeeScript 1.6.3
(function() {
  var insta_url;

  insta_url = "https://api.instagram.com/v1/users/176654965/media/recent/?client_id=6b9b2c56a73245399348a8063866dfb6";

}).call(this);
